# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Handbook of Rhetorical Devices
author: Robert A. Harris
amazon_url: https://www.amazon.com/gp/product/1884585485?ie=UTF8&tag=virtualsalt-20&linkCode=as2&camp=1789&creative=390957&creativeASIN=1884585485

email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  More than sixty traditional rhetorical devices, all of which can still be useful today to improve the effectiveness, clarity, and enjoyment of your writing.
  
baseurl: "/virtualsaltrhetorics" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title:output_ext

# Build settings
markdown: kramdown
  
# theme: ed.
remote_theme: minicomp/ed

plugins:
  - jekyll-feed
  - jekyll-paginate
  
paginate: 7

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "figure"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
